# fly.toml app configuration file generated for restoreab on 2023-12-28T08:59:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restoreab"
primary_region = "otp"

[build]
  image = "antebucan/restore:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__PublishableKey = "pk_test_51MXt69KlCGHoRojPc1KR25dQY7S9FHViXhqpVdwtYiOuyemFOLqJdJ0YV1Vr99scCxLGOMzdKBx7PpcOxOxB9EPm00BPaHFhCs"
  Cloudinary__CloudName = "dyplf7nyb"
  Cloudinary__ApiKey = "915185836251192"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
